import z from 'zod';

// helper function
const convertStringToArray = (val) => {
  if (typeof val === 'string') {
    return val
      .split(',')
      .map((item) => item.trim())
      .filter(Boolean);
  }
  return Array.isArray(val) ? val : [];
};

// helper function for generate time only year
export const generateYearOptions = (startOffset = 0, yearsCount = 50) => {
  const currentYear = new Date().getFullYear();
  return Array.from({ length: yearsCount }, (_, i) => {
    const year = (currentYear - startOffset + i).toString();
    return {
      label: year,
      value: year,
    };
  });
};

// helper image rules
const MAX_FILE_SIZE = 1 * 1024 * 1024; // 1 MB in Bytes
const ACCEPTED_IMAGE_TYPES = [
  'image/jpeg',
  'image/jpg',
  'image/png',
  'image/webp',
];

// STEP 1 SCHEMA: ACCOUNT
export const step1Schema = z.object({
  nama_lengkap: z.string().min(1, 'Nama lengkap wajib diisi'),
  nomor_porsi: z.string().min(1, 'Nomor porsi wajib diisi'),
  whatsapp: z.string().min(1, 'Nomor WhatsApp wajib diisi'),
  role: z.string().min(1, 'Role Wajib diisi'),
  password: z.string().min(6, 'Password minimal 6 karakter'),
});

export const roleOptions = [
  { label: 'Jamaah', value: 'user' },
  { label: 'Pembimbing', value: 'pembimbing' },
  { label: 'Admin', value: 'admin' },
];

// STEP 2 SCHEMA: PROFILE BIODATA
export const step2Schema = z.object({
  fatherName: z
    .string()
    .min(1, 'Nama ayah kandung wajib diisi')
    .min(3, 'Nama ayah kandung minimal 3 karakter'),
  birthDate: z.string().min(1, 'Tanggal lahir wajib diisi'),
  gender: z.preprocess(
    (val) => (val === null || val === undefined ? '' : val),
    z.string().min(1, 'Jenis kelamin wajib diisi'),
  ),
  birthPlace: z.string().min(1, 'Pilih tempat/kota kelahiran'),
  address: z
    .string()
    .min(1, 'Alamat wajib diisi')
    .min(5, 'Alamat lengkap minimal 5 karakter'),
  subDistrict: z.string().min(1, 'Kecamatan wajib diisi'),
  village: z.string().min(1, 'Desa/Kelurahan wajib diisi'),
  profileImage: z
    .any()
    .refine(
      (file) => file !== null && file !== undefined,
      'Foto profile wajib diunggah',
    )
    .refine((file) => {
      if (file instanceof File) return file.size <= MAX_FILE_SIZE;
      return true; // Jika berupa string URL (mode edit)
    }, 'Ukuran file maksimal 1 MB')
    .refine((file) => {
      if (file instanceof File) return ACCEPTED_IMAGE_TYPES.includes(file.type);
      return true;
    }, 'Format file harus JPG, PNG, atau WEBP'),
  job: z.string().min(1, 'Pekerjaan wajib diisi'),
  education: z.string().nullable().optional(),
  departure: z.string().min(1, 'Program keberangkatan wajib diisi'),
  experience: z.string().min(1, 'Pengalaman wajib diisi'),
  companion: z.string().min(1, 'Pendamping wajib diisi'),
  mahramName: z.string().min(1, 'Nama mahram wajib diisi'),
  expertise: z.preprocess(
    convertStringToArray,
    z.array(z.string()).min(1, 'Masukkan minimal satu kemampuan yang dikuasai'),
  ),
  contribution: z.preprocess(
    convertStringToArray,
    z
      .array(z.string())
      .min(1, 'Masukkan minimal satu hal positif yang dikontribusikan'),
  ),
  health: z.preprocess(
    convertStringToArray,
    z
      .array(z.string())
      .min(1, 'Masukkan minimal satu kondisi kesehatan atau kebutuhan khusus'),
  ),
  referenceName: z.string().nullable().optional(),
  referencePhone: z.string().nullable().optional(),
  referenceOrigin: z.string().nullable().optional(),
});

// STEP 3 SCHEMA: BUREAUCRACY AND DOCUMENTS
export const step3Schema = z.object({
  currPortionPosition: z.coerce.string().nullable().optional(),
  currPortionStatus: z.string().nullable().optional(),
  zone: z.string().min(1, 'Zona wajib diisi'),
  googleFormStatus: z.string().nullable().optional(),
  photoStatus: z.string().nullable().optional(),
  spphStatus: z.string().nullable().optional(),
  mutationStatus: z.string().nullable().optional(),
  biometricStatus: z.string().nullable().optional(),
  puskesmasStatus: z.string().nullable().optional(),
  mcuStatus: z.string().nullable().optional(),
  paymentStatus: z.string().nullable().optional(),
  passport: z.string().nullable().optional(),
  statusPassport: z.string().nullable().optional(),
  visa: z.string().nullable().optional(),
  statusVisa: z.string().nullable().optional(),
  plotNumber: z.string().nullable().optional(),
  batch: z.string().nullable().optional(),
  group: z.string().nullable().optional(),
  team: z.string().nullable().optional(),
});

// DATA SUPPORT
export const cityOptions = [
  { label: 'Kab. Aceh Barat', value: 'kab_aceh_barat' },
  { label: 'Kab. Aceh Barat Daya', value: 'kab_aceh_barat_daya' },
  { label: 'Kab. Aceh Besar', value: 'kab_aceh_besar' },
  { label: 'Kab. Aceh Jaya', value: 'kab_aceh_jaya' },
  { label: 'Kab. Aceh Selatan', value: 'kab_aceh_selatan' },
  { label: 'Kab. Aceh Singkil', value: 'kab_aceh_singkil' },
  { label: 'Kab. Aceh Tamiang', value: 'kab_aceh_tamiang' },
  { label: 'Kab. Aceh Tengah', value: 'kab_aceh_tengah' },
  { label: 'Kab. Aceh Tenggara', value: 'kab_aceh_tenggara' },
  { label: 'Kab. Aceh Timur', value: 'kab_aceh_timur' },
  { label: 'Kab. Aceh Utara', value: 'kab_aceh_utara' },
  { label: 'Kab. Agam', value: 'kab_agam' },
  { label: 'Kab. Alor', value: 'kab_alor' },
  { label: 'Kab. Asahan', value: 'kab_asahan' },
  { label: 'Kab. Asmat', value: 'kab_asmat' },
  { label: 'Kab. Badung', value: 'kab_badung' },
  { label: 'Kab. Balangan', value: 'kab_balangan' },
  { label: 'Kab. Bandung', value: 'kab_bandung' },
  { label: 'Kab. Bandung Barat', value: 'kab_bandung_barat' },
  { label: 'Kab. Banggai', value: 'kab_banggai' },
  { label: 'Kab. Banggai Kepulauan', value: 'kab_banggai_kepulauan' },
  { label: 'Kab. Banggai Laut', value: 'kab_banggai_laut' },
  { label: 'Kab. Bangka', value: 'kab_bangka' },
  { label: 'Kab. Bangka Barat', value: 'kab_bangka_barat' },
  { label: 'Kab. Bangka Selatan', value: 'kab_bangka_selatan' },
  { label: 'Kab. Bangka Tengah', value: 'kab_bangka_tengah' },
  { label: 'Kab. Bangkalan', value: 'kab_bangkalan' },
  { label: 'Kab. Bangli', value: 'kab_bangli' },
  { label: 'Kab. Banjar', value: 'kab_banjar' },
  { label: 'Kab. Banjarnegara', value: 'kab_banjarnegara' },
  { label: 'Kab. Bantaeng', value: 'kab_bantaeng' },
  { label: 'Kab. Bantul', value: 'kab_bantul' },
  { label: 'Kab. Banyuasin', value: 'kab_banyuasin' },
  { label: 'Kab. Banyumas', value: 'kab_banyumas' },
  { label: 'Kab. Banyuwangi', value: 'kab_banyuwangi' },
  { label: 'Kab. Barito Selatan', value: 'kab_barito_selatan' },
  { label: 'Kab. Barito Timur', value: 'kab_barito_timur' },
  { label: 'Kab. Barito Utara', value: 'kab_barito_utara' },
  { label: 'Kab. Barru', value: 'kab_barru' },
  { label: 'Kab. Batang', value: 'kab_batang' },
  { label: 'Kab. Batanghari', value: 'kab_batanghari' },
  { label: 'Kab. Batu Bara', value: 'kab_batu_bara' },
  { label: 'Kab. Beliu', value: 'kab_belu' },
  { label: 'Kab. Bener Meriah', value: 'kab_bener_meriah' },
  { label: 'Kab. Bengkalis', value: 'kab_bengkalis' },
  { label: 'Kab. Bengkayang', value: 'kab_bengkayang' },
  { label: 'Kab. Bengkulu Selatan', value: 'kab_bengkulu_selatan' },
  { label: 'Kab. Bengkulu Tengah', value: 'kab_bengkulu_tengah' },
  { label: 'Kab. Bengkulu Utara', value: 'kab_bengkulu_utara' },
  { label: 'Kab. Berau', value: 'kab_berau' },
  { label: 'Kab. Biak Numfor', value: 'kab_biak_numfor' },
  { label: 'Kab. Bima', value: 'kab_bima' },
  { label: 'Kab. Bintan', value: 'kab_bintan' },
  { label: 'Kab. Bireuen', value: 'kab_bireuen' },
  { label: 'Kab. Blitar', value: 'kab_blitar' },
  { label: 'Kab. Blora', value: 'kab_blora' },
  { label: 'Kab. Boalemo', value: 'kab_boalemo' },
  { label: 'Kab. Bogor', value: 'kab_bogor' },
  { label: 'Kab. Bojonegoro', value: 'kab_bojonegoro' },
  { label: 'Kab. Bolaang Mongondow', value: 'kab_bolaang_mongondow' },
  {
    label: 'Kab. Bolaang Mongondow Selatan',
    value: 'kab_bolaang_mongondow_selatan',
  },
  {
    label: 'Kab. Bolaang Mongondow Timur',
    value: 'kab_bolaang_mongondow_timur',
  },
  {
    label: 'Kab. Bolaang Mongondow Utara',
    value: 'kab_bolaang_mongondow_utara',
  },
  { label: 'Kab. Bombana', value: 'kab_bombana' },
  { label: 'Kab. Bondowoso', value: 'kab_bondowoso' },
  { label: 'Kab. Bone', value: 'kab_bone' },
  { label: 'Kab. Bone Bolango', value: 'kab_bone_bolango' },
  { label: 'Kab. Boven Digoel', value: 'kab_boven_digoel' },
  { label: 'Kab. Boyolali', value: 'kab_boyolali' },
  { label: 'Kab. Brebes', value: 'kab_brebes' },
  { label: 'Kab. Buol', value: 'kab_buol' },
  { label: 'Kab. Buru', value: 'kab_buru' },
  { label: 'Kab. Buru Selatan', value: 'kab_buru_selatan' },
  { label: 'Kab. Buton', value: 'kab_buton' },
  { label: 'Kab. Buton Selatan', value: 'kab_buton_selatan' },
  { label: 'Kab. Buton Tengah', value: 'kab_buton_tengah' },
  { label: 'Kab. Buton Utara', value: 'kab_buton_utara' },
  { label: 'Kab. Ciamis', value: 'kab_ciamis' },
  { label: 'Kab. Cianjur', value: 'kab_cianjur' },
  { label: 'Kab. Cilacap', value: 'kab_cilacap' },
  { label: 'Kab. Cirebon', value: 'kab_cirebon' },
  { label: 'Kab. Dairi', value: 'kab_dairi' },
  { label: 'Kab. Deiyai', value: 'kab_deiyai' },
  { label: 'Kab. Deli Serdang', value: 'kab_deli_serdang' },
  { label: 'Kab. Demak', value: 'kab_demak' },
  { label: 'Kab. Dharmasraya', value: 'kab_dharmasraya' },
  { label: 'Kab. Dogiyai', value: 'kab_dogiyai' },
  { label: 'Kab. Dompu', value: 'kab_dompu' },
  { label: 'Kab. Donggala', value: 'kab_donggala' },
  { label: 'Kab. Empat Lawang', value: 'kab_empat_lawang' },
  { label: 'Kab. Ende', value: 'kab_ende' },
  { label: 'Kab. Enrekang', value: 'kab_enrekang' },
  { label: 'Kab. Fakfak', value: 'kab_fakfak' },
  { label: 'Kab. Flores Timur', value: 'kab_flores_timur' },
  { label: 'Kab. Garut', value: 'kab_garut' },
  { label: 'Kab. Gayo Lues', value: 'kab_gayo_lues' },
  { label: 'Kab. Gianyar', value: 'kab_gianyar' },
  { label: 'Kab. Gorontalo', value: 'kab_gorontalo' },
  { label: 'Kab. Gorontalo Utara', value: 'kab_gorontalo_utara' },
  { label: 'Kab. Gowa', value: 'kab_gowa' },
  { label: 'Kab. Gresik', value: 'kab_gresik' },
  { label: 'Kab. Grobogan', value: 'kab_grobogan' },
  { label: 'Kab. Gunung Mas', value: 'kab_gunung_mas' },
  { label: 'Kab. Gunungkidul', value: 'kab_gunungkidul' },
  { label: 'Kab. Halmahera Barat', value: 'kab_halmahera_barat' },
  { label: 'Kab. Halmahera Selatan', value: 'kab_halmahera_selatan' },
  { label: 'Kab. Halmahera Tengah', value: 'kab_halmahera_tengah' },
  { label: 'Kab. Halmahera Timur', value: 'kab_halmahera_timur' },
  { label: 'Kab. Halmahera Utara', value: 'kab_halmahera_utara' },
  { label: 'Kab. Hulu Sungai Selatan', value: 'kab_hulu_sungai_selatan' },
  { label: 'Kab. Hulu Sungai Tengah', value: 'kab_hulu_sungai_tengah' },
  { label: 'Kab. Hulu Sungai Utara', value: 'kab_hulu_sungai_utara' },
  { label: 'Kab. Humbang Hasundutan', value: 'kab_humbang_hasundutan' },
  { label: 'Kab. Indragiri Hilir', value: 'kab_indragiri_hilir' },
  { label: 'Kab. Indragiri Hulu', value: 'kab_indragiri_hulu' },
  { label: 'Kab. Indramayu', value: 'kab_indramayu' },
  { label: 'Kab. Intan Jaya', value: 'kab_intan_jaya' },
  { label: 'Kab. Jayapura', value: 'kab_jayapura' },
  { label: 'Kab. Jayawijaya', value: 'kab_jayawijaya' },
  { label: 'Kab. Jember', value: 'kab_jember' },
  { label: 'Kab. Jembrana', value: 'kab_jembrana' },
  { label: 'Kab. Jeneponto', value: 'kab_jeneponto' },
  { label: 'Kab. Jepara', value: 'kab_jepara' },
  { label: 'Kab. Jombang', value: 'kab_jombang' },
  { label: 'Kab. Kaimana', value: 'kab_kaimana' },
  { label: 'Kab. Kampar', value: 'kab_kampar' },
  { label: 'Kab. Kapuas', value: 'kab_kapuas' },
  { label: 'Kab. Kapuas Hulu', value: 'kab_kapuas_hulu' },
  { label: 'Kab. Karanganyar', value: 'kab_karanganyar' },
  { label: 'Kab. Karangasem', value: 'kab_karangasem' },
  { label: 'Kab. Karawang', value: 'kab_karawang' },
  { label: 'Kab. Karimun', value: 'kab_karimun' },
  { label: 'Kab. Karo', value: 'kab_karo' },
  { label: 'Kab. Katingan', value: 'kab_katingan' },
  { label: 'Kab. Kaur', value: 'kab_kaur' },
  { label: 'Kab. Kayong Utara', value: 'kab_kayong_utara' },
  { label: 'Kab. Kebumen', value: 'kab_kebumen' },
  { label: 'Kab. Kediri', value: 'kab_kediri' },
  { label: 'Kab. Keerom', value: 'kab_keerom' },
  { label: 'Kab. Kendal', value: 'kab_kendal' },
  { label: 'Kab. Kepahiang', value: 'kab_kepahiang' },
  { label: 'Kab. Kepulauan Anambas', value: 'kab_kepulauan_anambas' },
  { label: 'Kab. Kepulauan Aru', value: 'kab_kepulauan_aru' },
  { label: 'Kab. Kepulauan Mentawai', value: 'kab_kepulauan_mentawai' },
  { label: 'Kab. Kepulauan Meranti', value: 'kab_kepulauan_meranti' },
  { label: 'Kab. Kepulauan Sangihe', value: 'kab_kepulauan_sangihe' },
  { label: 'Kab. Kepulauan Selayar', value: 'kab_kepulauan_selayar' },
  {
    label: 'Kab. Kepulauan Siau Tagulandang Biaro',
    value: 'kab_kepulauan_siau_tagulandang_biaro',
  },
  { label: 'Kab. Kepulauan Sula', value: 'kab_kepulauan_sula' },
  { label: 'Kab. Kepulauan Tanimbar', value: 'kab_kepulauan_tanimbar' },
  { label: 'Kab. Kepulauan Talaud', value: 'kab_kepulauan_talaud' },
  { label: 'Kab. Kepulauan Yapen', value: 'kab_kepulauan_yapen' },
  { label: 'Kab. Kerinci', value: 'kab_kerinci' },
  { label: 'Kab. Ketapang', value: 'kab_ketapang' },
  { label: 'Kab. Klaten', value: 'kab_klaten' },
  { label: 'Kab. Klungkung', value: 'kab_klungkung' },
  { label: 'Kab. Kolaka', value: 'kab_kolaka' },
  { label: 'Kab. Kolaka Timur', value: 'kab_kolaka_timur' },
  { label: 'Kab. Kolaka Utara', value: 'kab_kolaka_utara' },
  { label: 'Kab. Konawe', value: 'kab_konawe' },
  { label: 'Kab. Konawe Kepulauan', value: 'kab_konawe_kepulauan' },
  { label: 'Kab. Konawe Selatan', value: 'kab_konawe_selatan' },
  { label: 'Kab. Konawe Utara', value: 'kab_konawe_utara' },
  { label: 'Kab. Kotawaringin Barat', value: 'kab_kotawaringin_barat' },
  { label: 'Kab. Kotawaringin Timur', value: 'kab_kotawaringin_timur' },
  { label: 'Kab. Kuantan Singingi', value: 'kab_kuantan_singingi' },
  { label: 'Kab. Kubu Raya', value: 'kab_kubu_raya' },
  { label: 'Kab. Kudus', value: 'kab_kudus' },
  { label: 'Kab. Kulon Progo', value: 'kab_kulon_progo' },
  { label: 'Kab. Kuningan', value: 'kab_kuningan' },
  { label: 'Kab. Kupang', value: 'kab_kupang' },
  { label: 'Kab. Kutai Barat', value: 'kab_kutai_barat' },
  { label: 'Kab. Kutai Kartanegara', value: 'kab_kutai_kartanegara' },
  { label: 'Kab. Kutai Timur', value: 'kab_kutai_timur' },
  { label: 'Kab. Labuhanbatu', value: 'kab_labuhanbatu' },
  { label: 'Kab. Labuhanbatu Selatan', value: 'kab_labuhanbatu_selatan' },
  { label: 'Kab. Labuhanbatu Utara', value: 'kab_labuhanbatu_utara' },
  { label: 'Kab. Lahat', value: 'kab_lahat' },
  { label: 'Kab. Lamandau', value: 'kab_lamandau' },
  { label: 'Kab. Lamongan', value: 'kab_lamongan' },
  { label: 'Kab. Lampung Barat', value: 'kab_lampung_barat' },
  { label: 'Kab. Lampung Selatan', value: 'kab_lampung_selatan' },
  { label: 'Kab. Lampung Tengah', value: 'kab_lampung_tengah' },
  { label: 'Kab. Lampung Timur', value: 'kab_lampung_timur' },
  { label: 'Kab. Lampung Utara', value: 'kab_lampung_utara' },
  { label: 'Kab. Landak', value: 'kab_landak' },
  { label: 'Kab. Langkat', value: 'kab_langkat' },
  { label: 'Kab. Lanny Jaya', value: 'kab_lanny_jaya' },
  { label: 'Kab. Lebak', value: 'kab_lebak' },
  { label: 'Kab. Lebong', value: 'kab_lebong' },
  { label: 'Kab. Lembata', value: 'kab_lembata' },
  { label: 'Kab. Lima Puluh Kota', value: 'kab_lima_puluh_kota' },
  { label: 'Kab. Lingga', value: 'kab_lingga' },
  { label: 'Kab. Lombok Barat', value: 'kab_lombok_barat' },
  { label: 'Kab. Lombok Tengah', value: 'kab_lombok_tengah' },
  { label: 'Kab. Lombok Timur', value: 'kab_lombok_timur' },
  { label: 'Kab. Lombok Utara', value: 'kab_lombok_utara' },
  { label: 'Kab. Lumajang', value: 'kab_lumajang' },
  { label: 'Kab. Luwu', value: 'kab_luwu' },
  { label: 'Kab. Luwu Timur', value: 'kab_luwu_timur' },
  { label: 'Kab. Luwu Utara', value: 'kab_luwu_utara' },
  { label: 'Kab. Madiun', value: 'kab_madiun' },
  { label: 'Kab. Magelang', value: 'kab_magelang' },
  { label: 'Kab. Magetan', value: 'kab_magetan' },
  { label: 'Kab. Mahakam Ulu', value: 'kab_mahakam_ulu' },
  { label: 'Kab. Majalengka', value: 'kab_majalengka' },
  { label: 'Kab. Majene', value: 'kab_majene' },
  { label: 'Kab. Malaka', value: 'kab_malaka' },
  { label: 'Kab. Malang', value: 'kab_malang' },
  { label: 'Kab. Malinau', value: 'kab_malinau' },
  { label: 'Kab. Maluku Barat Daya', value: 'kab_maluku_barat_daya' },
  { label: 'Kab. Maluku Tengah', value: 'kab_maluku_tengah' },
  { label: 'Kab. Maluku Tenggara', value: 'kab_maluku_tenggara' },
  { label: 'Kab. Mamasa', value: 'kab_mamasa' },
  { label: 'Kab. Mamberamo Raya', value: 'kab_mamberamo_raya' },
  { label: 'Kab. Mamberamo Tengah', value: 'kab_mamberamo_tengah' },
  { label: 'Kab. Mamuju', value: 'kab_mamuju' },
  { label: 'Kab. Mamuju Tengah', value: 'kab_mamuju_tengah' },
  { label: 'Kab. Manokwari', value: 'kab_manokwari' },
  { label: 'Kab. Manokwari Selatan', value: 'kab_manokwari_selatan' },
  { label: 'Kab. Mappi', value: 'kab_mappi' },
  { label: 'Kab. Maros', value: 'kab_maros' },
  { label: 'Kab. Maybrat', value: 'kab_maybrat' },
  { label: 'Kab. Merangin', value: 'kab_merangin' },
  { label: 'Kab. Merauke', value: 'kab_merauke' },
  { label: 'Kab. Minahasa', value: 'kab_minahasa' },
  { label: 'Kab. Minahasa Selatan', value: 'kab_minahasa_selatan' },
  { label: 'Kab. Minahasa Tenggara', value: 'kab_minahasa_tenggara' },
  { label: 'Kab. Minahasa Utara', value: 'kab_minahasa_utara' },
  { label: 'Kab. Mojokerto', value: 'kab_mojokerto' },
  { label: 'Kab. Morowali', value: 'kab_morowali' },
  { label: 'Kab. Morowali Utara', value: 'kab_morowali_utara' },
  { label: 'Kab. Muara Enim', value: 'kab_muara_enim' },
  { label: 'Kab. Muaro Jambi', value: 'kab_muaro_jambi' },
  { label: 'Kab. Muko Muko', value: 'kab_muko_muko' },
  { label: 'Kab. Muna', value: 'kab_muna' },
  { label: 'Kab. Muna Barat', value: 'kab_muna_barat' },
  { label: 'Kab. Murung Raya', value: 'kab_murung_raya' },
  { label: 'Kab. Musi Banyuasin', value: 'kab_musi_banyuasin' },
  { label: 'Kab. Musi Rawas', value: 'kab_musi_rawas' },
  { label: 'Kab. Musi Rawas Utara', value: 'kab_musi_rawas_utara' },
  { label: 'Kab. Nabire', value: 'kab_nabire' },
  { label: 'Kab. Nagan Raya', value: 'kab_nagan_raya' },
  { label: 'Kab. Nagekeo', value: 'kab_nagekeo' },
  { label: 'Kab. Natuna', value: 'kab_natuna' },
  { label: 'Kab. Nduga', value: 'kab_nduga' },
  { label: 'Kab. Ngada', value: 'kab_ngada' },
  { label: 'Kab. Nganjuk', value: 'kab_nganjuk' },
  { label: 'Kab. Ngawi', value: 'kab_ngawi' },
  { label: 'Kab. Nias', value: 'kab_nias' },
  { label: 'Kab. Nias Barat', value: 'kab_nias_barat' },
  { label: 'Kab. Nias Selatan', value: 'kab_nias_selatan' },
  { label: 'Kab. Nias Utara', value: 'kab_nias_utara' },
  { label: 'Kab. Nunukan', value: 'kab_nunukan' },
  { label: 'Kab. Ogan Ilir', value: 'kab_ogan_ilir' },
  { label: 'Kab. Ogan Komering Ilir', value: 'kab_ogan_komering_ilir' },
  { label: 'Kab. Ogan Komering Ulu', value: 'kab_ogan_komering_ulu' },
  {
    label: 'Kab. Ogan Komering Ulu Selatan',
    value: 'kab_ogan_komering_ulu_selatan',
  },
  {
    label: 'Kab. Ogan Komering Ulu Timur',
    value: 'kab_ogan_komering_ulu_timur',
  },
  { label: 'Kab. Pacitan', value: 'kab_pacitan' },
  { label: 'Kab. Padang Lawas', value: 'kab_padang_lawas' },
  { label: 'Kab. Padang Lawas Utara', value: 'kab_padang_lawas_utara' },
  { label: 'Kab. Padang Pariaman', value: 'kab_padang_pariaman' },
  { label: 'Kab. Pakpak Bharat', value: 'kab_pakpak_bharat' },
  { label: 'Kab. Pamekasan', value: 'kab_pamekasan' },
  { label: 'Kab. Pandeglang', value: 'kab_pandeglang' },
  { label: 'Kab. Pangandaran', value: 'kab_pangandaran' },
  {
    label: 'Kab. Pangkajene dan Kepulauan',
    value: 'kab_pangkajene_dan_kepulauan',
  },
  { label: 'Kab. Pasaman', value: 'kab_pasaman' },
  { label: 'Kab. Pasaman Barat', value: 'kab_pasaman_barat' },
  { label: 'Kab. Paser', value: 'kab_paser' },
  { label: 'Kab. Pasuruan', value: 'kab_pasuruan' },
  { label: 'Kab. Pati', value: 'kab_pati' },
  { label: 'Kab. Pegunungan Arfak', value: 'kab_pegunungan_arfak' },
  { label: 'Kab. Pegunungan Bintang', value: 'kab_pegunungan_bintang' },
  { label: 'Kab. Pekalongan', value: 'kab_pekalongan' },
  { label: 'Kab. Pelalawan', value: 'kab_pelalawan' },
  { label: 'Kab. Pemalang', value: 'kab_pemalang' },
  { label: 'Kab. Penajam Paser Utara', value: 'kab_penajam_paser_utara' },
  {
    label: 'Kab. Penukal Abab Lematang Ilir',
    value: 'kab_penukal_abab_lematang_ilir',
  },
  { label: 'Kab. Pesawaran', value: 'kab_pesawaran' },
  { label: 'Kab. Pesisir Barat', value: 'kab_pesisir_barat' },
  { label: 'Kab. Pesisir Selatan', value: 'kab_pesisir_selatan' },
  { label: 'Kab. Pidie', value: 'kab_pidie' },
  { label: 'Kab. Pidie Jaya', value: 'kab_pidie_jaya' },
  { label: 'Kab. Pinrang', value: 'kab_pinrang' },
  { label: 'Kab. Pohuwato', value: 'kab_pohuwato' },
  { label: 'Kab. Polewali Mandar', value: 'kab_polewali_mandar' },
  { label: 'Kab. Ponorogo', value: 'kab_ponorogo' },
  { label: 'Kab. Mempawah', value: 'kab_mempawah' },
  { label: 'Kab. Poso', value: 'kab_poso' },
  { label: 'Kab. Pringsewu', value: 'kab_pringsewu' },
  { label: 'Kab. Probolinggo', value: 'kab_probolinggo' },
  { label: 'Kab. Pulang Pisau', value: 'kab_pulang_pisau' },
  { label: 'Kab. Pulau Morotai', value: 'kab_pulau_morotai' },
  { label: 'Kab. Pulau Taliabu', value: 'kab_pulau_taliabu' },
  { label: 'Kab. Puncak', value: 'kab_puncak' },
  { label: 'Kab. Puncak Jaya', value: 'kab_puncak_jaya' },
  { label: 'Kab. Purbalingga', value: 'kab_purbalingga' },
  { label: 'Kab. Purwakarta', value: 'kab_purwakarta' },
  { label: 'Kab. Purworejo', value: 'kab_purworejo' },
  { label: 'Kab. Raja Ampat', value: 'kab_raja_ampat' },
  { label: 'Kab. Rejang Lebong', value: 'kab_rejang_lebong' },
  { label: 'Kab. Rembang', value: 'kab_rembang' },
  { label: 'Kab. Rokan Hilir', value: 'kab_rokan_hilir' },
  { label: 'Kab. Rokan Hulu', value: 'kab_rokan_hulu' },
  { label: 'Kab. Rote Ndao', value: 'kab_rote_ndao' },
  { label: 'Kab. Sabu Raijua', value: 'kab_sabu_raijua' },
  { label: 'Kab. Sambas', value: 'kab_sambas' },
  { label: 'Kab. Samosir', value: 'kab_samosir' },
  { label: 'Kab. Sampang', value: 'kab_sampang' },
  { label: 'Kab. Sanggau', value: 'kab_sanggau' },
  { label: 'Kab. Sarmi', value: 'kab_sarmi' },
  { label: 'Kab. Sarolangun', value: 'kab_sarolangun' },
  { label: 'Kab. Sekadau', value: 'kab_sekadau' },
  { label: 'Kab. Seluma', value: 'kab_seluma' },
  { label: 'Kab. Semarang', value: 'kab_semarang' },
  { label: 'Kab. Seram Bagian Barat', value: 'kab_seram_bagian_barat' },
  { label: 'Kab. Seram Bagian Timur', value: 'kab_seram_bagian_timur' },
  { label: 'Kab. Serang', value: 'kab_serang' },
  { label: 'Kab. Serdang Bedagai', value: 'kab_serdang_bedagai' },
  { label: 'Kab. Seruyan', value: 'kab_seruyan' },
  { label: 'Kab. Siak', value: 'kab_siak' },
  { label: 'Kab. Sidenreng Rappang', value: 'kab_sidenreng_rappang' },
  { label: 'Kab. Sidoarjo', value: 'kab_sidoarjo' },
  { label: 'Kab. Sigi', value: 'kab_sigi' },
  { label: 'Kab. Sijunjung', value: 'kab_sijunjung' },
  { label: 'Kab. Sikka', value: 'kab_sikka' },
  { label: 'Kab. Simalungun', value: 'kab_simalungun' },
  { label: 'Kab. Simeulue', value: 'kab_simeulue' },
  { label: 'Kab. Sinjai', value: 'kab_sinjai' },
  { label: 'Kab. Sintang', value: 'kab_sintang' },
  { label: 'Kab. Situbondo', value: 'kab_situbondo' },
  { label: 'Kab. Sleman', value: 'kab_sleman' },
  { label: 'Kab. Solok', value: 'kab_solok' },
  { label: 'Kab. Solok Selatan', value: 'kab_solok_selatan' },
  { label: 'Kab. Soppeng', value: 'kab_soppeng' },
  { label: 'Kab. Sorong', value: 'kab_sorong' },
  { label: 'Kab. Sorong Selatan', value: 'kab_sorong_selatan' },
  { label: 'Kab. Sragen', value: 'kab_sragen' },
  { label: 'Kab. Subang', value: 'kab_subang' },
  { label: 'Kab. Sukabumi', value: 'kab_sukabumi' },
  { label: 'Kab. Sukamara', value: 'kab_sukamara' },
  { label: 'Kab. Sukoharjo', value: 'kab_sukoharjo' },
  { label: 'Kab. Sumba Barat', value: 'kab_sumba_barat' },
  { label: 'Kab. Sumba Barat Daya', value: 'kab_sumba_barat_daya' },
  { label: 'Kab. Sumba Tengah', value: 'kab_sumba_tengah' },
  { label: 'Kab. Sumba Timur', value: 'kab_sumba_timur' },
  { label: 'Kab. Sumbawa', value: 'kab_sumbawa' },
  { label: 'Kab. Sumbawa Barat', value: 'kab_sumbawa_barat' },
  { label: 'Kab. Sumedang', value: 'kab_sumedang' },
  { label: 'Kab. Sumenep', value: 'kab_sumenep' },
  { label: 'Kab. Supiori', value: 'kab_supiori' },
  { label: 'Kab. Tabalong', value: 'kab_tabalong' },
  { label: 'Kab. Tabanan', value: 'kab_tabanan' },
  { label: 'Kab. Takalar', value: 'kab_takalar' },
  { label: 'Kab. Tambrauw', value: 'kab_tambrauw' },
  { label: 'Kab. Tana Tidung', value: 'kab_tana_tidung' },
  { label: 'Kab. Tana Toraja', value: 'kab_tana_toraja' },
  { label: 'Kab. Tanah Bumbu', value: 'kab_tanah_bumbu' },
  { label: 'Kab. Tanah Datar', value: 'kab_tanah_datar' },
  { label: 'Kab. Tanah Laut', value: 'kab_tanah_laut' },
  { label: 'Kab. Tangerang', value: 'kab_tangerang' },
  { label: 'Kab. Tanggamus', value: 'kab_tanggamus' },
  { label: 'Kab. Tanjung Jabung Barat', value: 'kab_tanjung_jabung_barat' },
  { label: 'Kab. Tanjung Jabung Timur', value: 'kab_tanjung_jabung_timur' },
  { label: 'Kab. Tapanuli Selatan', value: 'kab_tapanuli_selatan' },
  { label: 'Kab. Tapanuli Tengah', value: 'kab_tapanuli_tengah' },
  { label: 'Kab. Tapanuli Utara', value: 'kab_tapanuli_utara' },
  { label: 'Kab. Tapin', value: 'kab_tapin' },
  { label: 'Kab. Tarakan', value: 'kab_tarakan' },
  { label: 'Kab. Tasikmalaya', value: 'kab_tasikmalaya' },
  { label: 'Kab. Toba', value: 'kab_toba' },
  { label: 'Kab. Tojo Una-Una', value: 'kab_tojo_una_una' },
  { label: 'Kab. Tolikara', value: 'kab_tolikara' },
  { label: 'Kab. Toli-Toli', value: 'kab_toli_toli' },
  { label: 'Kab. Toraja Utara', value: 'kab_toraja_utara' },
  { label: 'Kab. Trenggalek', value: 'kab_trenggalek' },
  { label: 'Kab. Tuban', value: 'kab_tuban' },
  { label: 'Kab. Tulang Bawang', value: 'kab_tulang_bawang' },
  { label: 'Kab. Tulang Bawang Barat', value: 'kab_tulang_bawang_barat' },
  { label: 'Kab. Tulungagung', value: 'kab_tulungagung' },
  { label: 'Kab. Wajo', value: 'kab_wajo' },
  { label: 'Kab. Wakatobi', value: 'kab_wakatobi' },
  { label: 'Kab. Waropen', value: 'kab_waropen' },
  { label: 'Kab. Way Kanan', value: 'kab_way_kanan' },
  { label: 'Kab. Wonogiri', value: 'kab_wonogiri' },
  { label: 'Kab. Wonosobo', value: 'kab_wonosobo' },
  { label: 'Kab. Yahukimo', value: 'kab_yahukimo' },
  { label: 'Kab. Yalimo', value: 'kab_yalimo' },
  { label: 'Kota Ambon', value: 'kota_ambon' },
  { label: 'Kota Balikpapan', value: 'kota_balikpapan' },
  { label: 'Kota Banda Aceh', value: 'kota_banda_aceh' },
  { label: 'Kota Bandar Lampung', value: 'kota_bandar_lampung' },
  { label: 'Kota Bandung', value: 'kota_bandung' },
  { label: 'Kota Banjar', value: 'kota_banjar' },
  { label: 'Kota Banjarbaru', value: 'kota_banjarbaru' },
  { label: 'Kota Banjarmasin', value: 'kota_banjarmasin' },
  { label: 'Kota Batam', value: 'kota_batam' },
  { label: 'Kota Batu', value: 'kota_batu' },
  { label: 'Kota Bau-Bau', value: 'kota_bau_bau' },
  { label: 'Kota Bekasi', value: 'kota_bekasi' },
  { label: 'Kota Bengkulu', value: 'kota_bengkulu' },
  { label: 'Kota Bima', value: 'kota_bima' },
  { label: 'Kota Binjai', value: 'kota_binjai' },
  { label: 'Kota Bitung', value: 'kota_bitung' },
  { label: 'Kota Blitar', value: 'kota_blitar' },
  { label: 'Kota Bogor', value: 'kota_bogor' },
  { label: 'Kota Bontang', value: 'kota_bontang' },
  { label: 'Kota Bukittinggi', value: 'kota_bukittinggi' },
  { label: 'Kota Cirebon', value: 'kota_cirebon' },
  { label: 'Kota Denpasar', value: 'kota_denpasar' },
  { label: 'Kota Depok', value: 'kota_depok' },
  { label: 'Kota Dumai', value: 'kota_dumai' },
  { label: 'Kota Gorontalo', value: 'kota_gorontalo' },
  { label: 'Kota Gunungsitoli', value: 'kota_gunungsitoli' },
  { label: 'Kota Jakarta Barat', value: 'kota_jakarta_barat' },
  { label: 'Kota Jakarta Pusat', value: 'kota_jakarta_pusat' },
  { label: 'Kota Jakarta Selatan', value: 'kota_jakarta_selatan' },
  { label: 'Kota Jakarta Timur', value: 'kota_jakarta_timur' },
  { label: 'Kota Jakarta Utara', value: 'kota_jakarta_utara' },
  { label: 'Kota Jambi', value: 'kota_jambi' },
  { label: 'Kota Jayapura', value: 'kota_jayapura' },
  { label: 'Kota Kediri', value: 'kota_kediri' },
  { label: 'Kota Kendari', value: 'kota_kendari' },
  { label: 'Kota Kotamobagu', value: 'kota_kotamobagu' },
  { label: 'Kota Kupang', value: 'kota_kupang' },
  { label: 'Kota Langsa', value: 'kota_langsa' },
  { label: 'Kota Lhokseumawe', value: 'kota_lhokseumawe' },
  { label: 'Kota Lubuklinggau', value: 'kota_lubuklinggau' },
  { label: 'Kota Madiun', value: 'kota_madiun' },
  { label: 'Kota Magelang', value: 'kota_magelang' },
  { label: 'Kota Makassar', value: 'kota_makassar' },
  { label: 'Kota Malang', value: 'kota_malang' },
  { label: 'Kota Manado', value: 'kota_manado' },
  { label: 'Kota Mataram', value: 'kota_mataram' },
  { label: 'Kota Medan', value: 'kota_medan' },
  { label: 'Kota Metro', value: 'kota_metro' },
  { label: 'Kota Mojokerto', value: 'kota_mojokerto' },
  { label: 'Kota Padang', value: 'kota_padang' },
  { label: 'Kota Padang Panjang', value: 'kota_padang_panjang' },
  { label: 'Kota Padangsidimpuan', value: 'kota_padangsidimpuan' },
  { label: 'Kota Pagar Alam', value: 'kota_pagar_alam' },
  { label: 'Kota Palangka Raya', value: 'kota_palangka_raya' },
  { label: 'Kota Palembang', value: 'kota_palembang' },
  { label: 'Kota Palopo', value: 'kota_palopo' },
  { label: 'Kota Palu', value: 'kota_palu' },
  { label: 'Kota Pangkalpinang', value: 'kota_pangkalpinang' },
  { label: 'Kota Parepare', value: 'kota_parepare' },
  { label: 'Kota Pariaman', value: 'kota_pariaman' },
  { label: 'Kota Pasuruan', value: 'kota_pasuruan' },
  { label: 'Kota Payakumbuh', value: 'kota_payakumbuh' },
  { label: 'Kota Pekalongan', value: 'kota_pekalongan' },
  { label: 'Kota Pekanbaru', value: 'kota_pekanbaru' },
  { label: 'Kota Pematangsiantar', value: 'kota_pematangsiantar' },
  { label: 'Kota Pontianak', value: 'kota_pontianak' },
  { label: 'Kota Prabumulih', value: 'kota_prabumulih' },
  { label: 'Kota Probolinggo', value: 'kota_probolinggo' },
  { label: 'Kota Sabang', value: 'kota_sabang' },
  { label: 'Kota Salatiga', value: 'kota_salatiga' },
  { label: 'Kota Samarinda', value: 'kota_samarinda' },
  { label: 'Kota Sawahlunto', value: 'kota_sawahlunto' },
  { label: 'Kota Semarang', value: 'kota_semarang' },
  { label: 'Kota Serang', value: 'kota_serang' },
  { label: 'Kota Sibolga', value: 'kota_sibolga' },
  { label: 'Kota Singkawang', value: 'kota_singkawang' },
  { label: 'Kota Solok', value: 'kota_solok' },
  { label: 'Kota Sorong', value: 'kota_sorong' },
  { label: 'Kota Subulussalam', value: 'kota_subulussalam' },
  { label: 'Kota Sukabumi', value: 'kota_sukabumi' },
  { label: 'Kota Sungai Penuh', value: 'kota_sungai_penuh' },
  { label: 'Kota Surakarta', value: 'kota_surakarta' },
  { label: 'Kota Surabaya', value: 'kota_surabaya' },
  { label: 'Kota Tangerang', value: 'kota_tangerang' },
  { label: 'Kota Tangerang Selatan', value: 'kota_tangerang_selatan' },
  { label: 'Kota Tanjungbalai', value: 'kota_tanjungbalai' },
  { label: 'Kota Tanjungpinang', value: 'kota_tanjungpinang' },
  { label: 'Kota Tarakan', value: 'kota_tarakan' },
  { label: 'Kota Tasikmalaya', value: 'kota_tasikmalaya' },
  { label: 'Kota Tebing Tinggi', value: 'kota_tebing_tinggi' },
  { label: 'Kota Ternate', value: 'kota_ternate' },
  { label: 'Kota Tidore Kepulauan', value: 'kota_tidore_kepulauan' },
  { label: 'Kota Tomohon', value: 'kota_tomohon' },
  { label: 'Kota Tual', value: 'kota_tual' },
  { label: 'Kota Yogyakarta', value: 'kota_yogyakarta' },
];

export const gender = [
  { label: 'Laki-laki', value: 'laki-laki' },
  { label: 'Perempuan', value: 'perempuan' },
];

export const districtOptions = [
  { label: 'Banyusari', value: 'BANYUSARI' },
  { label: 'Batujaya', value: 'BATUJAYA' },
  { label: 'Ciampel', value: 'CIAMPEL' },
  { label: 'Cibuaya', value: 'CIBUAYA' },
  { label: 'Cikampek', value: 'CIKAMPEK' },
  { label: 'Cilamaya Kulon', value: 'CILAMAYA KULON' },
  { label: 'Cilamaya Wetan', value: 'CILAMAYA WETAN' },
  { label: 'Cilebar', value: 'CILEBAR' },
  { label: 'Jatisari', value: 'JATISARI' },
  { label: 'Jayakerta', value: 'JAYAKERTA' },
  { label: 'Karawang Barat', value: 'KARAWANG BARAT' },
  { label: 'Karawang Timur', value: 'KARAWANG TIMUR' },
  { label: 'Klari', value: 'KLARI' },
  { label: 'Kutawaluya', value: 'KUTAWALUYA' },
  { label: 'Lemahabang', value: 'LEMAHABANG' },
  { label: 'Majalaya', value: 'MAJALAYA' },
  { label: 'Pakisjaya', value: 'PAKISJAYA' },
  { label: 'Pangkalan', value: 'PANGKALAN' },
  { label: 'Pedes', value: 'PEDES' },
  { label: 'Purwasari', value: 'PURWASARI' },
  { label: 'Rawamerta', value: 'RAWAMERTA' },
  { label: 'Rengasdengklok', value: 'RENGASDENGKLOK' },
  { label: 'Tegalwaru', value: 'TEGALWARU' },
  { label: 'Telagasari', value: 'TELAGASARI' },
  { label: 'Telukjambe Barat', value: 'TELUKJAMBE BARAT' },
  { label: 'Telukjambe Timur', value: 'TELUKJAMBE TIMUR' },
  { label: 'Tempuran', value: 'TEMPURAN' },
  { label: 'Tirtajaya', value: 'TIRTAJAYA' },
  { label: 'Tirtamulya', value: 'TIRTAMULYA' },
  { label: 'Kotabaru', value: 'KOTABARU' },
];

export const educationOptions = [
  { label: 'Tidak Sekolah / Belum Sekolah', value: 'tidak_sekolah' },
  { label: 'Tidak Lulus SD', value: 'tidak_lulus-sd' },

  // --- PENDIDIKAN DASAR & MENENGAH ---
  { label: 'SD / MI', value: 'sd' },
  { label: 'SMP / Mts (SLTP)', value: 'sltp' },
  { label: ' SMA / SMK / MA (SLTA)', value: 'slta' },

  // --- PENDIDIKAN TINGGI ---
  { label: 'Diploma (D1/D2/D3/D4)', value: 'diploma' },
  { label: 'Strata 1 (S1)', value: 's1' },
  { label: 'Strata 2 (S2)', value: 's2' },
  { label: 'Strata 3 (S3)', value: 's3' },
];

export const statusPortionOptions = [
  { label: 'Cadangan 1', value: 'cadangan 1' },
  { label: 'Cadangan 2', value: 'cadangan 2' },
  { label: 'Cadangan 3', value: 'cadangan 3' },
];

export const statusControlProcessOptions = [
  { label: 'Menunggu', value: 'menunggu' },
  { label: 'Ok', value: 'ok' },
];

export const statusHajiUmrahOptions = [
  { label: 'Pernah Haji', value: 'pernah_haji' },
  { label: 'Pernah Umrah', value: 'pernah_umrah' },
  { label: 'Belum Pernah', value: 'belum_pernah' },
];

export const zonaOptions = [
  { label: 'A', value: 'A' },
  { label: 'B', value: 'B' },
  { label: 'C', value: 'C' },
  { label: 'D', value: 'D' },
  { label: 'E', value: 'E' },
  { label: 'F', value: 'F' },
];

export const UpdateUserSchema = z.object({
  fullName: z.string().nullable().optional(),
  portionNumber: z.string().nullable().optional(),
  whatsapp: z.string().nullable().optional(),
  fatherName: z.string().nullable().optional(),
  birthDate: z.string().nullable().optional(),
  gender: z.string().nullable().optional(),
  birthPlace: z.string().nullable().optional(),
  address: z.string().nullable().optional(),
  subDistrict: z.string().nullable().optional(),
  village: z.string().nullable().optional(),
  profileImage: z.string().nullable().optional(),
  job: z.string().nullable().optional(),
  education: z.string().nullable().optional(),

  departure: z.string().nullable().optional(),
  experience: z.string().nullable().optional(),
  health: z.string().nullable().optional(),
  expertise: z.string().nullable().optional(),
  contribution: z.string().nullable().optional(),

  companion: z.string().nullable().optional(),
  mahramName: z.string().nullable().optional(),
  referenceName: z.string().nullable().optional(),
  referencePhone: z.string().nullable().optional(),
  referenceOrigin: z.string().nullable().optional(),

  currPortionPosition: z.string().nullable().optional(),
  currPorttionStatus: generateYearOptions(0, 50),

  zone: z.string().nullable().optional(),
  plotNumber: z.string().nullable().optional(),
  batch: z.string().nullable().optional(),
  group: z.string().nullable().optional(),
  team: z.string().nullable().optional(),

  googleFormStatus: z.string().nullable().optional(),
  photoStatus: z.string().nullable().optional(),
  spphStatus: z.string().nullable().optional(),
  mutationStatus: z.string().nullable().optional(),
  biometricStatus: z.string().nullable().optional(),
  puskesmasStatus: z.string().nullable().optional(),
  mcuStatus: z.string().nullable().optional(),
  paymentStatus: z.string().nullable().optional(),
  passport: z.string().nullable().optional(),
  statusPassport: z.string().nullable().optional(),
  visa: z.string().nullable().optional(),
  statusVisa: z.string().nullable().optional(),
});

// Konfimasi password didahalam user profile
export const updatePasswordSchemas = z

  .object({
    newPassword: z.string().min(8, 'Password baru minimal harus 8 karakter'),
    confirmPassword: z.string().min(1, 'Konfirmasi password harus diisi'),
  })
  .refine((data) => data.newPassword === data.confirmPassword, {
    message: 'Konfirmasi password tidak cocok dengan password baru',
    path: ['confirmPassword'],
  });
